<?php

namespace ContainerJTWYLFQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T6ro_NAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.t6ro.NA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.t6ro.NA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'evennement' => ['privates', '.errored..service_locator.t6ro.NA.App\\Entity\\Evennement', NULL, 'Cannot autowire service ".service_locator.t6ro.NA": it references class "App\\Entity\\Evennement" but no such service exists.'],
            'evennementRepository' => ['privates', 'App\\Repository\\EvennementRepository', 'getEvennementRepositoryService', true],
        ], [
            'evennement' => 'App\\Entity\\Evennement',
            'evennementRepository' => 'App\\Repository\\EvennementRepository',
        ]);
    }
}
