<?php

namespace ContainerJTWYLFQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ho9aMJBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ho9aMJB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ho9aMJB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'badge' => ['privates', '.errored..service_locator.Ho9aMJB.App\\Entity\\Badge', NULL, 'Cannot autowire service ".service_locator.Ho9aMJB": it references class "App\\Entity\\Badge" but no such service exists.'],
        ], [
            'badge' => 'App\\Entity\\Badge',
        ]);
    }
}
