<?php

namespace ContainerJTWYLFQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U2SNk1IService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.U2SNk1I' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.U2SNk1I'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reclamationAvi' => ['privates', '.errored..service_locator.U2SNk1I.App\\Entity\\ReclamationAvis', NULL, 'Cannot autowire service ".service_locator.U2SNk1I": it references class "App\\Entity\\ReclamationAvis" but no such service exists.'],
            'reclamationAvisRepository' => ['privates', 'App\\Repository\\ReclamationAvisRepository', 'getReclamationAvisRepositoryService', true],
        ], [
            'reclamationAvi' => 'App\\Entity\\ReclamationAvis',
            'reclamationAvisRepository' => 'App\\Repository\\ReclamationAvisRepository',
        ]);
    }
}
