<?php

namespace ContainerJTWYLFQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HZ34ZWkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HZ34ZWk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HZ34ZWk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'candidature' => ['privates', '.errored..service_locator.HZ34ZWk.App\\Entity\\Candidature', NULL, 'Cannot autowire service ".service_locator.HZ34ZWk": it references class "App\\Entity\\Candidature" but no such service exists.'],
            'candidatureRepository' => ['privates', 'App\\Repository\\CandidatureRepository', 'getCandidatureRepositoryService', true],
        ], [
            'candidature' => 'App\\Entity\\Candidature',
            'candidatureRepository' => 'App\\Repository\\CandidatureRepository',
        ]);
    }
}
