<?php

namespace ContainerJTWYLFQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J1ENEuIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.j1ENEuI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.j1ENEuI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'adsRepository' => ['privates', 'App\\Repository\\AdsRepository', 'getAdsRepositoryService', true],
        ], [
            'adsRepository' => 'App\\Repository\\AdsRepository',
        ]);
    }
}
