<?php

namespace ContainerJTWYLFQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1zF6Fn7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1zF6Fn7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1zF6Fn7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'certificationRepository' => ['privates', 'App\\Repository\\CertificationRepository', 'getCertificationRepositoryService', true],
        ], [
            'certificationRepository' => 'App\\Repository\\CertificationRepository',
        ]);
    }
}
