<?php

namespace ContainerJTWYLFQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LBkDBibService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lBkDBib' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lBkDBib'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'candidatureRepository' => ['privates', 'App\\Repository\\CandidatureRepository', 'getCandidatureRepositoryService', true],
        ], [
            'candidatureRepository' => 'App\\Repository\\CandidatureRepository',
        ]);
    }
}
