<?php

namespace ContainerJTWYLFQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ES08SJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eS08S_J' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eS08S_J'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'contrat' => ['privates', '.errored..service_locator.eS08S_J.App\\Entity\\Contrat', NULL, 'Cannot autowire service ".service_locator.eS08S_J": it references class "App\\Entity\\Contrat" but no such service exists.'],
        ], [
            'contrat' => 'App\\Entity\\Contrat',
        ]);
    }
}
