<?php

namespace ContainerJTWYLFQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I7zfSvnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i7zfSvn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i7zfSvn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'certifBadge' => ['privates', '.errored..service_locator.i7zfSvn.App\\Entity\\CertifBadge', NULL, 'Cannot autowire service ".service_locator.i7zfSvn": it references class "App\\Entity\\CertifBadge" but no such service exists.'],
        ], [
            'certifBadge' => 'App\\Entity\\CertifBadge',
        ]);
    }
}
