<?php

namespace ContainerJTWYLFQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AXjo5hZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aXjo5hZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aXjo5hZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'certifBadgeRepository' => ['privates', 'App\\Repository\\CertifBadgeRepository', 'getCertifBadgeRepositoryService', true],
        ], [
            'certifBadgeRepository' => 'App\\Repository\\CertifBadgeRepository',
        ]);
    }
}
