<?php

namespace ContainerJTWYLFQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBadgeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.20cMmfJ.App\Entity\Badge' shared service.
     *
     * @return \App\Entity\Badge
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.20cMmfJ": it references class "App\\Entity\\Badge" but no such service exists.');
    }
}
