<?php

namespace ContainerJTWYLFQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContrat2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.eS08S_J.App\Entity\Contrat' shared service.
     *
     * @return \App\Entity\Contrat
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.eS08S_J": it references class "App\\Entity\\Contrat" but no such service exists.');
    }
}
