<?php

namespace ContainerJTWYLFQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCandidature2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.V9dIZoj.App\Entity\Candidature' shared service.
     *
     * @return \App\Entity\Candidature
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.V9dIZoj": it references class "App\\Entity\\Candidature" but no such service exists.');
    }
}
