<?php

namespace ContainerJTWYLFQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCaptchaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..UQWdkq.App\Entity\Captcha' shared service.
     *
     * @return \App\Entity\Captcha
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator..UQWdkq": it references class "App\\Entity\\Captcha" but no such service exists.');
    }
}
