<?php

namespace ContainerJTWYLFQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntretien2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.v0.Vwio.App\Entity\Entretien' shared service.
     *
     * @return \App\Entity\Entretien
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.v0.Vwio": it references class "App\\Entity\\Entretien" but no such service exists.');
    }
}
