<?php

namespace ContainerJTWYLFQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuizService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.by1YEBl.App\Entity\Quiz' shared service.
     *
     * @return \App\Entity\Quiz
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.by1YEBl": it references class "App\\Entity\\Quiz" but no such service exists.');
    }
}
