<?php

namespace ContainerJTWYLFQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReclamationAvis2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.U2SNk1I.App\Entity\ReclamationAvis' shared service.
     *
     * @return \App\Entity\ReclamationAvis
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.U2SNk1I": it references class "App\\Entity\\ReclamationAvis" but no such service exists.');
    }
}
