<?php

namespace ContainerGTbZEYW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YRa9tnDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YRa9tnD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YRa9tnD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sponsor' => ['privates', '.errored..service_locator.YRa9tnD.App\\Entity\\Sponsor', NULL, 'Cannot autowire service ".service_locator.YRa9tnD": it references class "App\\Entity\\Sponsor" but no such service exists.'],
            'sponsorRepository' => ['privates', 'App\\Repository\\SponsorRepository', 'getSponsorRepositoryService', true],
        ], [
            'sponsor' => 'App\\Entity\\Sponsor',
            'sponsorRepository' => 'App\\Repository\\SponsorRepository',
        ]);
    }
}
