<?php

namespace ContainerGTbZEYW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__UQWdkqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..UQWdkq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..UQWdkq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'captcha' => ['privates', '.errored..service_locator..UQWdkq.App\\Entity\\Captcha', NULL, 'Cannot autowire service ".service_locator..UQWdkq": it references class "App\\Entity\\Captcha" but no such service exists.'],
        ], [
            'captcha' => 'App\\Entity\\Captcha',
        ]);
    }
}
