<?php

namespace ContainerGTbZEYW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HMUAAHFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HMUAAHF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HMUAAHF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'evennementRepository' => ['privates', 'App\\Repository\\EvennementRepository', 'getEvennementRepositoryService', true],
        ], [
            'evennementRepository' => 'App\\Repository\\EvennementRepository',
        ]);
    }
}
