<?php

namespace ContainerGTbZEYW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_By1YEBlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.by1YEBl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.by1YEBl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'quiz' => ['privates', '.errored..service_locator.by1YEBl.App\\Entity\\Quiz', NULL, 'Cannot autowire service ".service_locator.by1YEBl": it references class "App\\Entity\\Quiz" but no such service exists.'],
        ], [
            'quiz' => 'App\\Entity\\Quiz',
        ]);
    }
}
