<?php

namespace ContainerGTbZEYW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Vp8H4JxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vp8H4Jx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vp8H4Jx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'test' => ['privates', '.errored..service_locator.vp8H4Jx.App\\Entity\\Test', NULL, 'Cannot autowire service ".service_locator.vp8H4Jx": it references class "App\\Entity\\Test" but no such service exists.'],
            'testRepository' => ['privates', 'App\\Repository\\TestRepository', 'getTestRepositoryService', true],
        ], [
            'test' => 'App\\Entity\\Test',
            'testRepository' => 'App\\Repository\\TestRepository',
        ]);
    }
}
