<?php

namespace ContainerGTbZEYW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HdE11yfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HdE11yf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HdE11yf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'testRepository' => ['privates', 'App\\Repository\\TestRepository', 'getTestRepositoryService', true],
        ], [
            'testRepository' => 'App\\Repository\\TestRepository',
        ]);
    }
}
