<?php

namespace ContainerGTbZEYW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E4GF4KmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e4GF4Km' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.e4GF4Km'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'questionReponse' => ['privates', '.errored..service_locator.e4GF4Km.App\\Entity\\QuestionReponse', NULL, 'Cannot autowire service ".service_locator.e4GF4Km": it references class "App\\Entity\\QuestionReponse" but no such service exists.'],
            'questionReponseRepository' => ['privates', 'App\\Repository\\QuestionReponseRepository', 'getQuestionReponseRepositoryService', true],
        ], [
            'questionReponse' => 'App\\Entity\\QuestionReponse',
            'questionReponseRepository' => 'App\\Repository\\QuestionReponseRepository',
        ]);
    }
}
