<?php

namespace ContainerGTbZEYW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V0_VwioService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.v0.Vwio' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.v0.Vwio'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entretien' => ['privates', '.errored..service_locator.v0.Vwio.App\\Entity\\Entretien', NULL, 'Cannot autowire service ".service_locator.v0.Vwio": it references class "App\\Entity\\Entretien" but no such service exists.'],
            'entretienRepository' => ['privates', 'App\\Repository\\EntretienRepository', 'getEntretienRepositoryService', true],
        ], [
            'entretien' => 'App\\Entity\\Entretien',
            'entretienRepository' => 'App\\Repository\\EntretienRepository',
        ]);
    }
}
