<?php

namespace ContainerGTbZEYW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Zald0cKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zald0cK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zald0cK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'certifBadge' => ['privates', '.errored..service_locator.zald0cK.App\\Entity\\CertifBadge', NULL, 'Cannot autowire service ".service_locator.zald0cK": it references class "App\\Entity\\CertifBadge" but no such service exists.'],
            'certifBadgeRepository' => ['privates', 'App\\Repository\\CertifBadgeRepository', 'getCertifBadgeRepositoryService', true],
        ], [
            'certifBadge' => 'App\\Entity\\CertifBadge',
            'certifBadgeRepository' => 'App\\Repository\\CertifBadgeRepository',
        ]);
    }
}
