<?php

namespace ContainerGTbZEYW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4cgthvcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4cgthvc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4cgthvc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'captcha' => ['privates', '.errored..service_locator.4cgthvc.App\\Entity\\Captcha', NULL, 'Cannot autowire service ".service_locator.4cgthvc": it references class "App\\Entity\\Captcha" but no such service exists.'],
            'captchaRepository' => ['privates', 'App\\Repository\\CaptchaRepository', 'getCaptchaRepositoryService', true],
        ], [
            'captcha' => 'App\\Entity\\Captcha',
            'captchaRepository' => 'App\\Repository\\CaptchaRepository',
        ]);
    }
}
