<?php

namespace ContainerGTbZEYW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4oDAgEZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4oDAgEZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4oDAgEZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categorie' => ['privates', '.errored..service_locator.4oDAgEZ.App\\Entity\\Categorie', NULL, 'Cannot autowire service ".service_locator.4oDAgEZ": it references class "App\\Entity\\Categorie" but no such service exists.'],
            'categorieRepository' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
        ], [
            'categorie' => 'App\\Entity\\Categorie',
            'categorieRepository' => 'App\\Repository\\CategorieRepository',
        ]);
    }
}
