<?php

namespace ContainerGTbZEYW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DOip6zGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DOip6zG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DOip6zG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reclamationAvisRepository' => ['privates', 'App\\Repository\\ReclamationAvisRepository', 'getReclamationAvisRepositoryService', true],
        ], [
            'reclamationAvisRepository' => 'App\\Repository\\ReclamationAvisRepository',
        ]);
    }
}
