<?php

namespace ContainerGTbZEYW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..D21kzr.App\Entity\Ads' shared service.
     *
     * @return \App\Entity\Ads
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator..D21kzr": it references class "App\\Entity\\Ads" but no such service exists.');
    }
}
