<?php

namespace ContainerGTbZEYW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCertification2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.X7N9BY7.App\Entity\Certification' shared service.
     *
     * @return \App\Entity\Certification
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.X7N9BY7": it references class "App\\Entity\\Certification" but no such service exists.');
    }
}
