<?php

namespace ContainerGTbZEYW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCertifBadge2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.zald0cK.App\Entity\CertifBadge' shared service.
     *
     * @return \App\Entity\CertifBadge
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.zald0cK": it references class "App\\Entity\\CertifBadge" but no such service exists.');
    }
}
