<?php

namespace ContainerGTbZEYW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvennement2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.t6ro.NA.App\Entity\Evennement' shared service.
     *
     * @return \App\Entity\Evennement
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.t6ro.NA": it references class "App\\Entity\\Evennement" but no such service exists.');
    }
}
