<?php

namespace ContainerGTbZEYW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParticipation2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.r.sZWL..App\Entity\Participation' shared service.
     *
     * @return \App\Entity\Participation
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.r.sZWL.": it references class "App\\Entity\\Participation" but no such service exists.');
    }
}
