<?php

namespace ContainerGTbZEYW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuestionReponseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ODYByBl.App\Entity\QuestionReponse' shared service.
     *
     * @return \App\Entity\QuestionReponse
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ODYByBl": it references class "App\\Entity\\QuestionReponse" but no such service exists.');
    }
}
