<?php

namespace ContainerGTbZEYW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.CgQzjRy.App\Entity\Test' shared service.
     *
     * @return \App\Entity\Test
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.CgQzjRy": it references class "App\\Entity\\Test" but no such service exists.');
    }
}
