<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJTWYLFQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJTWYLFQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJTWYLFQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJTWYLFQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJTWYLFQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'JTWYLFQ',
    'container.build_id' => '21c830f5',
    'container.build_time' => 1668030022,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJTWYLFQ');
