<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO7uIOjC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO7uIOjC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO7uIOjC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO7uIOjC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO7uIOjC\App_KernelDevDebugContainer([
    'container.build_hash' => 'O7uIOjC',
    'container.build_id' => 'e4f43850',
    'container.build_time' => 1668091027,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO7uIOjC');
